/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.types;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ExecType { 
  New, PartiallyFilled, Filled, DoneForDay, Canceled, Replace, PendingCancel, Stopped, Rejected, Suspended, PendingNew, Calculated, Expired, Restated, PendingReplace  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ExecType\",\"namespace\":\"com.cyanspring.avro.types\",\"symbols\":[\"New\",\"PartiallyFilled\",\"Filled\",\"DoneForDay\",\"Canceled\",\"Replace\",\"PendingCancel\",\"Stopped\",\"Rejected\",\"Suspended\",\"PendingNew\",\"Calculated\",\"Expired\",\"Restated\",\"PendingReplace\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
