/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.types;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderType { 
  Market, Limit  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderType\",\"namespace\":\"com.cyanspring.avro.types\",\"symbols\":[\"Market\",\"Limit\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
