// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.trade.types
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public enum TimeInForce
	{
		Day,
		GoodTillCancel,
		AtTheOpening,
		ImmediateOrCancel,
		FillOrKill,
		GoodTillCrossing,
		GoodTillDate,
		AtTheClose,
	}
}
