/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.generate.market.bean;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Quote extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Quote\",\"namespace\":\"com.cyanspring.avro.generate.market.bean\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bid\",\"type\":\"double\"},{\"name\":\"ask\",\"type\":\"double\"},{\"name\":\"bidVol\",\"type\":\"double\"},{\"name\":\"askVol\",\"type\":\"double\"},{\"name\":\"last\",\"type\":\"double\"},{\"name\":\"lastVol\",\"type\":\"double\"},{\"name\":\"turnover\",\"type\":\"double\"},{\"name\":\"high\",\"type\":\"double\"},{\"name\":\"low\",\"type\":\"double\"},{\"name\":\"open\",\"type\":\"double\"},{\"name\":\"close\",\"type\":\"double\"},{\"name\":\"totalVolume\",\"type\":\"double\"},{\"name\":\"timeStamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timeSent\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"stale\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int objectType;
  @Deprecated public java.lang.String symbol;
  @Deprecated public double bid;
  @Deprecated public double ask;
  @Deprecated public double bidVol;
  @Deprecated public double askVol;
  @Deprecated public double last;
  @Deprecated public double lastVol;
  @Deprecated public double turnover;
  @Deprecated public double high;
  @Deprecated public double low;
  @Deprecated public double open;
  @Deprecated public double close;
  @Deprecated public double totalVolume;
  @Deprecated public java.lang.String timeStamp;
  @Deprecated public java.lang.String timeSent;
  @Deprecated public boolean stale;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Quote() {}

  /**
   * All-args constructor.
   */
  public Quote(java.lang.Integer objectType, java.lang.String symbol, java.lang.Double bid, java.lang.Double ask, java.lang.Double bidVol, java.lang.Double askVol, java.lang.Double last, java.lang.Double lastVol, java.lang.Double turnover, java.lang.Double high, java.lang.Double low, java.lang.Double open, java.lang.Double close, java.lang.Double totalVolume, java.lang.String timeStamp, java.lang.String timeSent, java.lang.Boolean stale) {
    this.objectType = objectType;
    this.symbol = symbol;
    this.bid = bid;
    this.ask = ask;
    this.bidVol = bidVol;
    this.askVol = askVol;
    this.last = last;
    this.lastVol = lastVol;
    this.turnover = turnover;
    this.high = high;
    this.low = low;
    this.open = open;
    this.close = close;
    this.totalVolume = totalVolume;
    this.timeStamp = timeStamp;
    this.timeSent = timeSent;
    this.stale = stale;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return objectType;
    case 1: return symbol;
    case 2: return bid;
    case 3: return ask;
    case 4: return bidVol;
    case 5: return askVol;
    case 6: return last;
    case 7: return lastVol;
    case 8: return turnover;
    case 9: return high;
    case 10: return low;
    case 11: return open;
    case 12: return close;
    case 13: return totalVolume;
    case 14: return timeStamp;
    case 15: return timeSent;
    case 16: return stale;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: objectType = (java.lang.Integer)value$; break;
    case 1: symbol = (java.lang.String)value$; break;
    case 2: bid = (java.lang.Double)value$; break;
    case 3: ask = (java.lang.Double)value$; break;
    case 4: bidVol = (java.lang.Double)value$; break;
    case 5: askVol = (java.lang.Double)value$; break;
    case 6: last = (java.lang.Double)value$; break;
    case 7: lastVol = (java.lang.Double)value$; break;
    case 8: turnover = (java.lang.Double)value$; break;
    case 9: high = (java.lang.Double)value$; break;
    case 10: low = (java.lang.Double)value$; break;
    case 11: open = (java.lang.Double)value$; break;
    case 12: close = (java.lang.Double)value$; break;
    case 13: totalVolume = (java.lang.Double)value$; break;
    case 14: timeStamp = (java.lang.String)value$; break;
    case 15: timeSent = (java.lang.String)value$; break;
    case 16: stale = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'objectType' field.
   */
  public java.lang.Integer getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the 'objectType' field.
   * @param value the value to set.
   */
  public void setObjectType(java.lang.Integer value) {
    this.objectType = value;
  }

  /**
   * Gets the value of the 'symbol' field.
   */
  public java.lang.String getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'bid' field.
   */
  public java.lang.Double getBid() {
    return bid;
  }

  /**
   * Sets the value of the 'bid' field.
   * @param value the value to set.
   */
  public void setBid(java.lang.Double value) {
    this.bid = value;
  }

  /**
   * Gets the value of the 'ask' field.
   */
  public java.lang.Double getAsk() {
    return ask;
  }

  /**
   * Sets the value of the 'ask' field.
   * @param value the value to set.
   */
  public void setAsk(java.lang.Double value) {
    this.ask = value;
  }

  /**
   * Gets the value of the 'bidVol' field.
   */
  public java.lang.Double getBidVol() {
    return bidVol;
  }

  /**
   * Sets the value of the 'bidVol' field.
   * @param value the value to set.
   */
  public void setBidVol(java.lang.Double value) {
    this.bidVol = value;
  }

  /**
   * Gets the value of the 'askVol' field.
   */
  public java.lang.Double getAskVol() {
    return askVol;
  }

  /**
   * Sets the value of the 'askVol' field.
   * @param value the value to set.
   */
  public void setAskVol(java.lang.Double value) {
    this.askVol = value;
  }

  /**
   * Gets the value of the 'last' field.
   */
  public java.lang.Double getLast() {
    return last;
  }

  /**
   * Sets the value of the 'last' field.
   * @param value the value to set.
   */
  public void setLast(java.lang.Double value) {
    this.last = value;
  }

  /**
   * Gets the value of the 'lastVol' field.
   */
  public java.lang.Double getLastVol() {
    return lastVol;
  }

  /**
   * Sets the value of the 'lastVol' field.
   * @param value the value to set.
   */
  public void setLastVol(java.lang.Double value) {
    this.lastVol = value;
  }

  /**
   * Gets the value of the 'turnover' field.
   */
  public java.lang.Double getTurnover() {
    return turnover;
  }

  /**
   * Sets the value of the 'turnover' field.
   * @param value the value to set.
   */
  public void setTurnover(java.lang.Double value) {
    this.turnover = value;
  }

  /**
   * Gets the value of the 'high' field.
   */
  public java.lang.Double getHigh() {
    return high;
  }

  /**
   * Sets the value of the 'high' field.
   * @param value the value to set.
   */
  public void setHigh(java.lang.Double value) {
    this.high = value;
  }

  /**
   * Gets the value of the 'low' field.
   */
  public java.lang.Double getLow() {
    return low;
  }

  /**
   * Sets the value of the 'low' field.
   * @param value the value to set.
   */
  public void setLow(java.lang.Double value) {
    this.low = value;
  }

  /**
   * Gets the value of the 'open' field.
   */
  public java.lang.Double getOpen() {
    return open;
  }

  /**
   * Sets the value of the 'open' field.
   * @param value the value to set.
   */
  public void setOpen(java.lang.Double value) {
    this.open = value;
  }

  /**
   * Gets the value of the 'close' field.
   */
  public java.lang.Double getClose() {
    return close;
  }

  /**
   * Sets the value of the 'close' field.
   * @param value the value to set.
   */
  public void setClose(java.lang.Double value) {
    this.close = value;
  }

  /**
   * Gets the value of the 'totalVolume' field.
   */
  public java.lang.Double getTotalVolume() {
    return totalVolume;
  }

  /**
   * Sets the value of the 'totalVolume' field.
   * @param value the value to set.
   */
  public void setTotalVolume(java.lang.Double value) {
    this.totalVolume = value;
  }

  /**
   * Gets the value of the 'timeStamp' field.
   */
  public java.lang.String getTimeStamp() {
    return timeStamp;
  }

  /**
   * Sets the value of the 'timeStamp' field.
   * @param value the value to set.
   */
  public void setTimeStamp(java.lang.String value) {
    this.timeStamp = value;
  }

  /**
   * Gets the value of the 'timeSent' field.
   */
  public java.lang.String getTimeSent() {
    return timeSent;
  }

  /**
   * Sets the value of the 'timeSent' field.
   * @param value the value to set.
   */
  public void setTimeSent(java.lang.String value) {
    this.timeSent = value;
  }

  /**
   * Gets the value of the 'stale' field.
   */
  public java.lang.Boolean getStale() {
    return stale;
  }

  /**
   * Sets the value of the 'stale' field.
   * @param value the value to set.
   */
  public void setStale(java.lang.Boolean value) {
    this.stale = value;
  }

  /** Creates a new Quote RecordBuilder */
  public static com.cyanspring.avro.generate.market.bean.Quote.Builder newBuilder() {
    return new com.cyanspring.avro.generate.market.bean.Quote.Builder();
  }
  
  /** Creates a new Quote RecordBuilder by copying an existing Builder */
  public static com.cyanspring.avro.generate.market.bean.Quote.Builder newBuilder(com.cyanspring.avro.generate.market.bean.Quote.Builder other) {
    return new com.cyanspring.avro.generate.market.bean.Quote.Builder(other);
  }
  
  /** Creates a new Quote RecordBuilder by copying an existing Quote instance */
  public static com.cyanspring.avro.generate.market.bean.Quote.Builder newBuilder(com.cyanspring.avro.generate.market.bean.Quote other) {
    return new com.cyanspring.avro.generate.market.bean.Quote.Builder(other);
  }
  
  /**
   * RecordBuilder for Quote instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Quote>
    implements org.apache.avro.data.RecordBuilder<Quote> {

    private int objectType;
    private java.lang.String symbol;
    private double bid;
    private double ask;
    private double bidVol;
    private double askVol;
    private double last;
    private double lastVol;
    private double turnover;
    private double high;
    private double low;
    private double open;
    private double close;
    private double totalVolume;
    private java.lang.String timeStamp;
    private java.lang.String timeSent;
    private boolean stale;

    /** Creates a new Builder */
    private Builder() {
      super(com.cyanspring.avro.generate.market.bean.Quote.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cyanspring.avro.generate.market.bean.Quote.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbol)) {
        this.symbol = data().deepCopy(fields()[1].schema(), other.symbol);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bid)) {
        this.bid = data().deepCopy(fields()[2].schema(), other.bid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ask)) {
        this.ask = data().deepCopy(fields()[3].schema(), other.ask);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.bidVol)) {
        this.bidVol = data().deepCopy(fields()[4].schema(), other.bidVol);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.askVol)) {
        this.askVol = data().deepCopy(fields()[5].schema(), other.askVol);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.last)) {
        this.last = data().deepCopy(fields()[6].schema(), other.last);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lastVol)) {
        this.lastVol = data().deepCopy(fields()[7].schema(), other.lastVol);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.turnover)) {
        this.turnover = data().deepCopy(fields()[8].schema(), other.turnover);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.high)) {
        this.high = data().deepCopy(fields()[9].schema(), other.high);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.low)) {
        this.low = data().deepCopy(fields()[10].schema(), other.low);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.open)) {
        this.open = data().deepCopy(fields()[11].schema(), other.open);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.close)) {
        this.close = data().deepCopy(fields()[12].schema(), other.close);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.totalVolume)) {
        this.totalVolume = data().deepCopy(fields()[13].schema(), other.totalVolume);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.timeStamp)) {
        this.timeStamp = data().deepCopy(fields()[14].schema(), other.timeStamp);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.timeSent)) {
        this.timeSent = data().deepCopy(fields()[15].schema(), other.timeSent);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.stale)) {
        this.stale = data().deepCopy(fields()[16].schema(), other.stale);
        fieldSetFlags()[16] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Quote instance */
    private Builder(com.cyanspring.avro.generate.market.bean.Quote other) {
            super(com.cyanspring.avro.generate.market.bean.Quote.SCHEMA$);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbol)) {
        this.symbol = data().deepCopy(fields()[1].schema(), other.symbol);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bid)) {
        this.bid = data().deepCopy(fields()[2].schema(), other.bid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ask)) {
        this.ask = data().deepCopy(fields()[3].schema(), other.ask);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.bidVol)) {
        this.bidVol = data().deepCopy(fields()[4].schema(), other.bidVol);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.askVol)) {
        this.askVol = data().deepCopy(fields()[5].schema(), other.askVol);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.last)) {
        this.last = data().deepCopy(fields()[6].schema(), other.last);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lastVol)) {
        this.lastVol = data().deepCopy(fields()[7].schema(), other.lastVol);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.turnover)) {
        this.turnover = data().deepCopy(fields()[8].schema(), other.turnover);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.high)) {
        this.high = data().deepCopy(fields()[9].schema(), other.high);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.low)) {
        this.low = data().deepCopy(fields()[10].schema(), other.low);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.open)) {
        this.open = data().deepCopy(fields()[11].schema(), other.open);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.close)) {
        this.close = data().deepCopy(fields()[12].schema(), other.close);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.totalVolume)) {
        this.totalVolume = data().deepCopy(fields()[13].schema(), other.totalVolume);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.timeStamp)) {
        this.timeStamp = data().deepCopy(fields()[14].schema(), other.timeStamp);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.timeSent)) {
        this.timeSent = data().deepCopy(fields()[15].schema(), other.timeSent);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.stale)) {
        this.stale = data().deepCopy(fields()[16].schema(), other.stale);
        fieldSetFlags()[16] = true;
      }
    }

    /** Gets the value of the 'objectType' field */
    public java.lang.Integer getObjectType() {
      return objectType;
    }
    
    /** Sets the value of the 'objectType' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setObjectType(int value) {
      validate(fields()[0], value);
      this.objectType = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'objectType' field has been set */
    public boolean hasObjectType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'objectType' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearObjectType() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'symbol' field */
    public java.lang.String getSymbol() {
      return symbol;
    }
    
    /** Sets the value of the 'symbol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setSymbol(java.lang.String value) {
      validate(fields()[1], value);
      this.symbol = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'symbol' field has been set */
    public boolean hasSymbol() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'symbol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'bid' field */
    public java.lang.Double getBid() {
      return bid;
    }
    
    /** Sets the value of the 'bid' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setBid(double value) {
      validate(fields()[2], value);
      this.bid = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'bid' field has been set */
    public boolean hasBid() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'bid' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearBid() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ask' field */
    public java.lang.Double getAsk() {
      return ask;
    }
    
    /** Sets the value of the 'ask' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setAsk(double value) {
      validate(fields()[3], value);
      this.ask = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ask' field has been set */
    public boolean hasAsk() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ask' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearAsk() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'bidVol' field */
    public java.lang.Double getBidVol() {
      return bidVol;
    }
    
    /** Sets the value of the 'bidVol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setBidVol(double value) {
      validate(fields()[4], value);
      this.bidVol = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'bidVol' field has been set */
    public boolean hasBidVol() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'bidVol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearBidVol() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'askVol' field */
    public java.lang.Double getAskVol() {
      return askVol;
    }
    
    /** Sets the value of the 'askVol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setAskVol(double value) {
      validate(fields()[5], value);
      this.askVol = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'askVol' field has been set */
    public boolean hasAskVol() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'askVol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearAskVol() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'last' field */
    public java.lang.Double getLast() {
      return last;
    }
    
    /** Sets the value of the 'last' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setLast(double value) {
      validate(fields()[6], value);
      this.last = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'last' field has been set */
    public boolean hasLast() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'last' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearLast() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'lastVol' field */
    public java.lang.Double getLastVol() {
      return lastVol;
    }
    
    /** Sets the value of the 'lastVol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setLastVol(double value) {
      validate(fields()[7], value);
      this.lastVol = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'lastVol' field has been set */
    public boolean hasLastVol() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'lastVol' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearLastVol() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'turnover' field */
    public java.lang.Double getTurnover() {
      return turnover;
    }
    
    /** Sets the value of the 'turnover' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setTurnover(double value) {
      validate(fields()[8], value);
      this.turnover = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'turnover' field has been set */
    public boolean hasTurnover() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'turnover' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearTurnover() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'high' field */
    public java.lang.Double getHigh() {
      return high;
    }
    
    /** Sets the value of the 'high' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setHigh(double value) {
      validate(fields()[9], value);
      this.high = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'high' field has been set */
    public boolean hasHigh() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'high' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearHigh() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'low' field */
    public java.lang.Double getLow() {
      return low;
    }
    
    /** Sets the value of the 'low' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setLow(double value) {
      validate(fields()[10], value);
      this.low = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'low' field has been set */
    public boolean hasLow() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'low' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearLow() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'open' field */
    public java.lang.Double getOpen() {
      return open;
    }
    
    /** Sets the value of the 'open' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setOpen(double value) {
      validate(fields()[11], value);
      this.open = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'open' field has been set */
    public boolean hasOpen() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'open' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearOpen() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'close' field */
    public java.lang.Double getClose() {
      return close;
    }
    
    /** Sets the value of the 'close' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setClose(double value) {
      validate(fields()[12], value);
      this.close = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'close' field has been set */
    public boolean hasClose() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'close' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearClose() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'totalVolume' field */
    public java.lang.Double getTotalVolume() {
      return totalVolume;
    }
    
    /** Sets the value of the 'totalVolume' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setTotalVolume(double value) {
      validate(fields()[13], value);
      this.totalVolume = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'totalVolume' field has been set */
    public boolean hasTotalVolume() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'totalVolume' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearTotalVolume() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'timeStamp' field */
    public java.lang.String getTimeStamp() {
      return timeStamp;
    }
    
    /** Sets the value of the 'timeStamp' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setTimeStamp(java.lang.String value) {
      validate(fields()[14], value);
      this.timeStamp = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'timeStamp' field has been set */
    public boolean hasTimeStamp() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'timeStamp' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearTimeStamp() {
      timeStamp = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'timeSent' field */
    public java.lang.String getTimeSent() {
      return timeSent;
    }
    
    /** Sets the value of the 'timeSent' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setTimeSent(java.lang.String value) {
      validate(fields()[15], value);
      this.timeSent = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'timeSent' field has been set */
    public boolean hasTimeSent() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'timeSent' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearTimeSent() {
      timeSent = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'stale' field */
    public java.lang.Boolean getStale() {
      return stale;
    }
    
    /** Sets the value of the 'stale' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder setStale(boolean value) {
      validate(fields()[16], value);
      this.stale = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'stale' field has been set */
    public boolean hasStale() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'stale' field */
    public com.cyanspring.avro.generate.market.bean.Quote.Builder clearStale() {
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    public Quote build() {
      try {
        Quote record = new Quote();
        record.objectType = fieldSetFlags()[0] ? this.objectType : (java.lang.Integer) defaultValue(fields()[0]);
        record.symbol = fieldSetFlags()[1] ? this.symbol : (java.lang.String) defaultValue(fields()[1]);
        record.bid = fieldSetFlags()[2] ? this.bid : (java.lang.Double) defaultValue(fields()[2]);
        record.ask = fieldSetFlags()[3] ? this.ask : (java.lang.Double) defaultValue(fields()[3]);
        record.bidVol = fieldSetFlags()[4] ? this.bidVol : (java.lang.Double) defaultValue(fields()[4]);
        record.askVol = fieldSetFlags()[5] ? this.askVol : (java.lang.Double) defaultValue(fields()[5]);
        record.last = fieldSetFlags()[6] ? this.last : (java.lang.Double) defaultValue(fields()[6]);
        record.lastVol = fieldSetFlags()[7] ? this.lastVol : (java.lang.Double) defaultValue(fields()[7]);
        record.turnover = fieldSetFlags()[8] ? this.turnover : (java.lang.Double) defaultValue(fields()[8]);
        record.high = fieldSetFlags()[9] ? this.high : (java.lang.Double) defaultValue(fields()[9]);
        record.low = fieldSetFlags()[10] ? this.low : (java.lang.Double) defaultValue(fields()[10]);
        record.open = fieldSetFlags()[11] ? this.open : (java.lang.Double) defaultValue(fields()[11]);
        record.close = fieldSetFlags()[12] ? this.close : (java.lang.Double) defaultValue(fields()[12]);
        record.totalVolume = fieldSetFlags()[13] ? this.totalVolume : (java.lang.Double) defaultValue(fields()[13]);
        record.timeStamp = fieldSetFlags()[14] ? this.timeStamp : (java.lang.String) defaultValue(fields()[14]);
        record.timeSent = fieldSetFlags()[15] ? this.timeSent : (java.lang.String) defaultValue(fields()[15]);
        record.stale = fieldSetFlags()[16] ? this.stale : (java.lang.Boolean) defaultValue(fields()[16]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
