// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.market.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Quote : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Quote"",""namespace"":""com.cyanspring.avro.generate.market.bean"",""fields"":[{""name"":""objectType"",""type"":""int""},{""name"":""symbol"",""type"":""string""},{""name"":""bid"",""type"":""double""},{""name"":""ask"",""type"":""double""},{""name"":""bidVol"",""type"":""double""},{""name"":""askVol"",""type"":""double""},{""name"":""last"",""type"":""double""},{""name"":""lastVol"",""type"":""double""},{""name"":""turnover"",""type"":""double""},{""name"":""high"",""type"":""double""},{""name"":""low"",""type"":""double""},{""name"":""open"",""type"":""double""},{""name"":""close"",""type"":""double""},{""name"":""totalVolume"",""type"":""double""},{""name"":""timeStamp"",""type"":""string""},{""name"":""timeSent"",""type"":""string""},{""name"":""stale"",""type"":""boolean""}]}");
		private int _objectType;
		private string _symbol;
		private double _bid;
		private double _ask;
		private double _bidVol;
		private double _askVol;
		private double _last;
		private double _lastVol;
		private double _turnover;
		private double _high;
		private double _low;
		private double _open;
		private double _close;
		private double _totalVolume;
		private string _timeStamp;
		private string _timeSent;
		private bool _stale;
		public virtual Schema Schema
		{
			get
			{
				return Quote._SCHEMA;
			}
		}
		public int objectType
		{
			get
			{
				return this._objectType;
			}
			set
			{
				this._objectType = value;
			}
		}
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				this._symbol = value;
			}
		}
		public double bid
		{
			get
			{
				return this._bid;
			}
			set
			{
				this._bid = value;
			}
		}
		public double ask
		{
			get
			{
				return this._ask;
			}
			set
			{
				this._ask = value;
			}
		}
		public double bidVol
		{
			get
			{
				return this._bidVol;
			}
			set
			{
				this._bidVol = value;
			}
		}
		public double askVol
		{
			get
			{
				return this._askVol;
			}
			set
			{
				this._askVol = value;
			}
		}
		public double last
		{
			get
			{
				return this._last;
			}
			set
			{
				this._last = value;
			}
		}
		public double lastVol
		{
			get
			{
				return this._lastVol;
			}
			set
			{
				this._lastVol = value;
			}
		}
		public double turnover
		{
			get
			{
				return this._turnover;
			}
			set
			{
				this._turnover = value;
			}
		}
		public double high
		{
			get
			{
				return this._high;
			}
			set
			{
				this._high = value;
			}
		}
		public double low
		{
			get
			{
				return this._low;
			}
			set
			{
				this._low = value;
			}
		}
		public double open
		{
			get
			{
				return this._open;
			}
			set
			{
				this._open = value;
			}
		}
		public double close
		{
			get
			{
				return this._close;
			}
			set
			{
				this._close = value;
			}
		}
		public double totalVolume
		{
			get
			{
				return this._totalVolume;
			}
			set
			{
				this._totalVolume = value;
			}
		}
		public string timeStamp
		{
			get
			{
				return this._timeStamp;
			}
			set
			{
				this._timeStamp = value;
			}
		}
		public string timeSent
		{
			get
			{
				return this._timeSent;
			}
			set
			{
				this._timeSent = value;
			}
		}
		public bool stale
		{
			get
			{
				return this._stale;
			}
			set
			{
				this._stale = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.objectType;
			case 1: return this.symbol;
			case 2: return this.bid;
			case 3: return this.ask;
			case 4: return this.bidVol;
			case 5: return this.askVol;
			case 6: return this.last;
			case 7: return this.lastVol;
			case 8: return this.turnover;
			case 9: return this.high;
			case 10: return this.low;
			case 11: return this.open;
			case 12: return this.close;
			case 13: return this.totalVolume;
			case 14: return this.timeStamp;
			case 15: return this.timeSent;
			case 16: return this.stale;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.objectType = (System.Int32)fieldValue; break;
			case 1: this.symbol = (System.String)fieldValue; break;
			case 2: this.bid = (System.Double)fieldValue; break;
			case 3: this.ask = (System.Double)fieldValue; break;
			case 4: this.bidVol = (System.Double)fieldValue; break;
			case 5: this.askVol = (System.Double)fieldValue; break;
			case 6: this.last = (System.Double)fieldValue; break;
			case 7: this.lastVol = (System.Double)fieldValue; break;
			case 8: this.turnover = (System.Double)fieldValue; break;
			case 9: this.high = (System.Double)fieldValue; break;
			case 10: this.low = (System.Double)fieldValue; break;
			case 11: this.open = (System.Double)fieldValue; break;
			case 12: this.close = (System.Double)fieldValue; break;
			case 13: this.totalVolume = (System.Double)fieldValue; break;
			case 14: this.timeStamp = (System.String)fieldValue; break;
			case 15: this.timeSent = (System.String)fieldValue; break;
			case 16: this.stale = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
