// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.@base.types
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public enum ObjectType
	{
		StateUpdate,
		OrderUpdate,
		NewOrderRequest,
		NewOrderReply,
		CancelOrderRequest,
		CancelOrderReply,
		AmendOrderReply,
		AmendOrderRequest,
		Quote,
		SubscribeQuote,
		UnsubscribeQuote,
	}
}
