// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.trade.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class CancelOrderRequest : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"CancelOrderRequest\",\"namespace\":\"com.cyanspring.avro.gen" +
				"erate.trade.bean\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"orderId\"" +
				",\"type\":\"string\"},{\"name\":\"exchangeAccount\",\"type\":\"string\"},{\"name\":\"txId\",\"typ" +
				"e\":\"string\"}]}");
		private int _objectType;
		private string _orderId;
		private string _exchangeAccount;
		private string _txId;
		public virtual Schema Schema
		{
			get
			{
				return CancelOrderRequest._SCHEMA;
			}
		}
		public int objectType
		{
			get
			{
				return this._objectType;
			}
			set
			{
				this._objectType = value;
			}
		}
		public string orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public string exchangeAccount
		{
			get
			{
				return this._exchangeAccount;
			}
			set
			{
				this._exchangeAccount = value;
			}
		}
		public string txId
		{
			get
			{
				return this._txId;
			}
			set
			{
				this._txId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.objectType;
			case 1: return this.orderId;
			case 2: return this.exchangeAccount;
			case 3: return this.txId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.objectType = (System.Int32)fieldValue; break;
			case 1: this.orderId = (System.String)fieldValue; break;
			case 2: this.exchangeAccount = (System.String)fieldValue; break;
			case 3: this.txId = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
