// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.trade.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class OrderUpdate : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderUpdate"",""namespace"":""com.cyanspring.avro.generate.trade.bean"",""fields"":[{""name"":""objectType"",""type"":""int""},{""name"":""orderId"",""type"":""string""},{""name"":""exchangeAccount"",""type"":""string""},{""name"":""exchangeOrderId"",""type"":""string""},{""name"":""symbol"",""type"":""string""},{""name"":""price"",""type"":""double""},{""name"":""quantity"",""type"":""double""},{""name"":""cumQty"",""type"":""double""},{""name"":""avgPx"",""type"":""double""},{""name"":""execType"",""type"":""int""},{""name"":""ordStatus"",""type"":""int""},{""name"":""orderSide"",""type"":""int""},{""name"":""orderType"",""type"":""int""},{""name"":""timeInForce"",""type"":""int""},{""name"":""created"",""type"":""string""},{""name"":""clOrderId"",""type"":""string""},{""name"":""txId"",""type"":""string""},{""name"":""msg"",""type"":""string""}]}");
		private int _objectType;
		private string _orderId;
		private string _exchangeAccount;
		private string _exchangeOrderId;
		private string _symbol;
		private double _price;
		private double _quantity;
		private double _cumQty;
		private double _avgPx;
		private int _execType;
		private int _ordStatus;
		private int _orderSide;
		private int _orderType;
		private int _timeInForce;
		private string _created;
		private string _clOrderId;
		private string _txId;
		private string _msg;
		public virtual Schema Schema
		{
			get
			{
				return OrderUpdate._SCHEMA;
			}
		}
		public int objectType
		{
			get
			{
				return this._objectType;
			}
			set
			{
				this._objectType = value;
			}
		}
		public string orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public string exchangeAccount
		{
			get
			{
				return this._exchangeAccount;
			}
			set
			{
				this._exchangeAccount = value;
			}
		}
		public string exchangeOrderId
		{
			get
			{
				return this._exchangeOrderId;
			}
			set
			{
				this._exchangeOrderId = value;
			}
		}
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				this._symbol = value;
			}
		}
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		public double cumQty
		{
			get
			{
				return this._cumQty;
			}
			set
			{
				this._cumQty = value;
			}
		}
		public double avgPx
		{
			get
			{
				return this._avgPx;
			}
			set
			{
				this._avgPx = value;
			}
		}
		public int execType
		{
			get
			{
				return this._execType;
			}
			set
			{
				this._execType = value;
			}
		}
		public int ordStatus
		{
			get
			{
				return this._ordStatus;
			}
			set
			{
				this._ordStatus = value;
			}
		}
		public int orderSide
		{
			get
			{
				return this._orderSide;
			}
			set
			{
				this._orderSide = value;
			}
		}
		public int orderType
		{
			get
			{
				return this._orderType;
			}
			set
			{
				this._orderType = value;
			}
		}
		public int timeInForce
		{
			get
			{
				return this._timeInForce;
			}
			set
			{
				this._timeInForce = value;
			}
		}
		public string created
		{
			get
			{
				return this._created;
			}
			set
			{
				this._created = value;
			}
		}
		public string clOrderId
		{
			get
			{
				return this._clOrderId;
			}
			set
			{
				this._clOrderId = value;
			}
		}
		public string txId
		{
			get
			{
				return this._txId;
			}
			set
			{
				this._txId = value;
			}
		}
		public string msg
		{
			get
			{
				return this._msg;
			}
			set
			{
				this._msg = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.objectType;
			case 1: return this.orderId;
			case 2: return this.exchangeAccount;
			case 3: return this.exchangeOrderId;
			case 4: return this.symbol;
			case 5: return this.price;
			case 6: return this.quantity;
			case 7: return this.cumQty;
			case 8: return this.avgPx;
			case 9: return this.execType;
			case 10: return this.ordStatus;
			case 11: return this.orderSide;
			case 12: return this.orderType;
			case 13: return this.timeInForce;
			case 14: return this.created;
			case 15: return this.clOrderId;
			case 16: return this.txId;
			case 17: return this.msg;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.objectType = (System.Int32)fieldValue; break;
			case 1: this.orderId = (System.String)fieldValue; break;
			case 2: this.exchangeAccount = (System.String)fieldValue; break;
			case 3: this.exchangeOrderId = (System.String)fieldValue; break;
			case 4: this.symbol = (System.String)fieldValue; break;
			case 5: this.price = (System.Double)fieldValue; break;
			case 6: this.quantity = (System.Double)fieldValue; break;
			case 7: this.cumQty = (System.Double)fieldValue; break;
			case 8: this.avgPx = (System.Double)fieldValue; break;
			case 9: this.execType = (System.Int32)fieldValue; break;
			case 10: this.ordStatus = (System.Int32)fieldValue; break;
			case 11: this.orderSide = (System.Int32)fieldValue; break;
			case 12: this.orderType = (System.Int32)fieldValue; break;
			case 13: this.timeInForce = (System.Int32)fieldValue; break;
			case 14: this.created = (System.String)fieldValue; break;
			case 15: this.clOrderId = (System.String)fieldValue; break;
			case 16: this.txId = (System.String)fieldValue; break;
			case 17: this.msg = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
