/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.generate.trade.types;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ObjectType { 
  NewOrderRequest, AmendOrderRequest, CancelOrderRequest, NewOrderReply, AmendOrderReply, CancelOrderReply, OrderUpdate  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ObjectType\",\"namespace\":\"com.cyanspring.avro.generate.trade.types\",\"symbols\":[\"NewOrderRequest\",\"AmendOrderRequest\",\"CancelOrderRequest\",\"NewOrderReply\",\"AmendOrderReply\",\"CancelOrderReply\",\"OrderUpdate\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
