/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.generate.trade.types;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderSide { 
  Buy, Sell  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderSide\",\"namespace\":\"com.cyanspring.avro.generate.trade.types\",\"symbols\":[\"Buy\",\"Sell\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
