/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.generate.trade.types;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrdStatus { 
  New, PartiallyFilled, Filled, DoneForDay, Canceled, Replaced, PendingCancel, Stopped, Rejected, Suspended, PendingNew, Calculated, Expired, AcceptedForBidding, PendingReplace  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrdStatus\",\"namespace\":\"com.cyanspring.avro.generate.trade.types\",\"symbols\":[\"New\",\"PartiallyFilled\",\"Filled\",\"DoneForDay\",\"Canceled\",\"Replaced\",\"PendingCancel\",\"Stopped\",\"Rejected\",\"Suspended\",\"PendingNew\",\"Calculated\",\"Expired\",\"AcceptedForBidding\",\"PendingReplace\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
