/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.generate.trade.types;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TimeInForce { 
  Day, GoodTillCancel, AtTheOpening, ImmediateOrCancel, FillOrKill, GoodTillCrossing, GoodTillDate, AtTheClose  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TimeInForce\",\"namespace\":\"com.cyanspring.avro.generate.trade.types\",\"symbols\":[\"Day\",\"GoodTillCancel\",\"AtTheOpening\",\"ImmediateOrCancel\",\"FillOrKill\",\"GoodTillCrossing\",\"GoodTillDate\",\"AtTheClose\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
