// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.market.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SubscribeQuote : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SubscribeQuote\",\"namespace\":\"com.cyanspring.avro.generat" +
				"e.market.bean\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"symbols\",\"t" +
				"ype\":{\"type\":\"array\",\"items\":\"string\"}}]}");
		private int _objectType;
		private IList<System.String> _symbols;
		public virtual Schema Schema
		{
			get
			{
				return SubscribeQuote._SCHEMA;
			}
		}
		public int objectType
		{
			get
			{
				return this._objectType;
			}
			set
			{
				this._objectType = value;
			}
		}
		public IList<System.String> symbols
		{
			get
			{
				return this._symbols;
			}
			set
			{
				this._symbols = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.objectType;
			case 1: return this.symbols;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.objectType = (System.Int32)fieldValue; break;
			case 1: this.symbols = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
