/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.trading;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CancelOrderRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CancelOrderRequest\",\"namespace\":\"com.cyanspring.avro.trading\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"txId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int objectType;
  @Deprecated public java.lang.String orderId;
  @Deprecated public java.lang.String txId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CancelOrderRequest() {}

  /**
   * All-args constructor.
   */
  public CancelOrderRequest(java.lang.Integer objectType, java.lang.String orderId, java.lang.String txId) {
    this.objectType = objectType;
    this.orderId = orderId;
    this.txId = txId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return objectType;
    case 1: return orderId;
    case 2: return txId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: objectType = (java.lang.Integer)value$; break;
    case 1: orderId = (java.lang.String)value$; break;
    case 2: txId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'objectType' field.
   */
  public java.lang.Integer getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the 'objectType' field.
   * @param value the value to set.
   */
  public void setObjectType(java.lang.Integer value) {
    this.objectType = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'txId' field.
   */
  public java.lang.String getTxId() {
    return txId;
  }

  /**
   * Sets the value of the 'txId' field.
   * @param value the value to set.
   */
  public void setTxId(java.lang.String value) {
    this.txId = value;
  }

  /** Creates a new CancelOrderRequest RecordBuilder */
  public static com.cyanspring.avro.trading.CancelOrderRequest.Builder newBuilder() {
    return new com.cyanspring.avro.trading.CancelOrderRequest.Builder();
  }
  
  /** Creates a new CancelOrderRequest RecordBuilder by copying an existing Builder */
  public static com.cyanspring.avro.trading.CancelOrderRequest.Builder newBuilder(com.cyanspring.avro.trading.CancelOrderRequest.Builder other) {
    return new com.cyanspring.avro.trading.CancelOrderRequest.Builder(other);
  }
  
  /** Creates a new CancelOrderRequest RecordBuilder by copying an existing CancelOrderRequest instance */
  public static com.cyanspring.avro.trading.CancelOrderRequest.Builder newBuilder(com.cyanspring.avro.trading.CancelOrderRequest other) {
    return new com.cyanspring.avro.trading.CancelOrderRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for CancelOrderRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CancelOrderRequest>
    implements org.apache.avro.data.RecordBuilder<CancelOrderRequest> {

    private int objectType;
    private java.lang.String orderId;
    private java.lang.String txId;

    /** Creates a new Builder */
    private Builder() {
      super(com.cyanspring.avro.trading.CancelOrderRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cyanspring.avro.trading.CancelOrderRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.txId)) {
        this.txId = data().deepCopy(fields()[2].schema(), other.txId);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CancelOrderRequest instance */
    private Builder(com.cyanspring.avro.trading.CancelOrderRequest other) {
            super(com.cyanspring.avro.trading.CancelOrderRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.txId)) {
        this.txId = data().deepCopy(fields()[2].schema(), other.txId);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'objectType' field */
    public java.lang.Integer getObjectType() {
      return objectType;
    }
    
    /** Sets the value of the 'objectType' field */
    public com.cyanspring.avro.trading.CancelOrderRequest.Builder setObjectType(int value) {
      validate(fields()[0], value);
      this.objectType = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'objectType' field has been set */
    public boolean hasObjectType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'objectType' field */
    public com.cyanspring.avro.trading.CancelOrderRequest.Builder clearObjectType() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'orderId' field */
    public java.lang.String getOrderId() {
      return orderId;
    }
    
    /** Sets the value of the 'orderId' field */
    public com.cyanspring.avro.trading.CancelOrderRequest.Builder setOrderId(java.lang.String value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'orderId' field has been set */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'orderId' field */
    public com.cyanspring.avro.trading.CancelOrderRequest.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'txId' field */
    public java.lang.String getTxId() {
      return txId;
    }
    
    /** Sets the value of the 'txId' field */
    public com.cyanspring.avro.trading.CancelOrderRequest.Builder setTxId(java.lang.String value) {
      validate(fields()[2], value);
      this.txId = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'txId' field has been set */
    public boolean hasTxId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'txId' field */
    public com.cyanspring.avro.trading.CancelOrderRequest.Builder clearTxId() {
      txId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public CancelOrderRequest build() {
      try {
        CancelOrderRequest record = new CancelOrderRequest();
        record.objectType = fieldSetFlags()[0] ? this.objectType : (java.lang.Integer) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.lang.String) defaultValue(fields()[1]);
        record.txId = fieldSetFlags()[2] ? this.txId : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
