/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.trading;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderUpdate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderUpdate\",\"namespace\":\"com.cyanspring.avro.trading\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"execType\",\"type\":\"int\"},{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ordStatus\",\"type\":\"int\"},{\"name\":\"orderSide\",\"type\":\"int\"},{\"name\":\"orderType\",\"type\":\"int\"},{\"name\":\"timeInForce\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"quantity\",\"type\":\"double\"},{\"name\":\"created\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"exchangeAccount\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"exchangeOrderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"clOrderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"txId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int objectType;
  @Deprecated public int execType;
  @Deprecated public java.lang.String symbol;
  @Deprecated public int ordStatus;
  @Deprecated public int orderSide;
  @Deprecated public int orderType;
  @Deprecated public int timeInForce;
  @Deprecated public double price;
  @Deprecated public double quantity;
  @Deprecated public java.lang.String created;
  @Deprecated public java.lang.String exchangeAccount;
  @Deprecated public java.lang.String exchangeOrderId;
  @Deprecated public java.lang.String clOrderId;
  @Deprecated public java.lang.String txId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public OrderUpdate() {}

  /**
   * All-args constructor.
   */
  public OrderUpdate(java.lang.Integer objectType, java.lang.Integer execType, java.lang.String symbol, java.lang.Integer ordStatus, java.lang.Integer orderSide, java.lang.Integer orderType, java.lang.Integer timeInForce, java.lang.Double price, java.lang.Double quantity, java.lang.String created, java.lang.String exchangeAccount, java.lang.String exchangeOrderId, java.lang.String clOrderId, java.lang.String txId) {
    this.objectType = objectType;
    this.execType = execType;
    this.symbol = symbol;
    this.ordStatus = ordStatus;
    this.orderSide = orderSide;
    this.orderType = orderType;
    this.timeInForce = timeInForce;
    this.price = price;
    this.quantity = quantity;
    this.created = created;
    this.exchangeAccount = exchangeAccount;
    this.exchangeOrderId = exchangeOrderId;
    this.clOrderId = clOrderId;
    this.txId = txId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return objectType;
    case 1: return execType;
    case 2: return symbol;
    case 3: return ordStatus;
    case 4: return orderSide;
    case 5: return orderType;
    case 6: return timeInForce;
    case 7: return price;
    case 8: return quantity;
    case 9: return created;
    case 10: return exchangeAccount;
    case 11: return exchangeOrderId;
    case 12: return clOrderId;
    case 13: return txId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: objectType = (java.lang.Integer)value$; break;
    case 1: execType = (java.lang.Integer)value$; break;
    case 2: symbol = (java.lang.String)value$; break;
    case 3: ordStatus = (java.lang.Integer)value$; break;
    case 4: orderSide = (java.lang.Integer)value$; break;
    case 5: orderType = (java.lang.Integer)value$; break;
    case 6: timeInForce = (java.lang.Integer)value$; break;
    case 7: price = (java.lang.Double)value$; break;
    case 8: quantity = (java.lang.Double)value$; break;
    case 9: created = (java.lang.String)value$; break;
    case 10: exchangeAccount = (java.lang.String)value$; break;
    case 11: exchangeOrderId = (java.lang.String)value$; break;
    case 12: clOrderId = (java.lang.String)value$; break;
    case 13: txId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'objectType' field.
   */
  public java.lang.Integer getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the 'objectType' field.
   * @param value the value to set.
   */
  public void setObjectType(java.lang.Integer value) {
    this.objectType = value;
  }

  /**
   * Gets the value of the 'execType' field.
   */
  public java.lang.Integer getExecType() {
    return execType;
  }

  /**
   * Sets the value of the 'execType' field.
   * @param value the value to set.
   */
  public void setExecType(java.lang.Integer value) {
    this.execType = value;
  }

  /**
   * Gets the value of the 'symbol' field.
   */
  public java.lang.String getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'ordStatus' field.
   */
  public java.lang.Integer getOrdStatus() {
    return ordStatus;
  }

  /**
   * Sets the value of the 'ordStatus' field.
   * @param value the value to set.
   */
  public void setOrdStatus(java.lang.Integer value) {
    this.ordStatus = value;
  }

  /**
   * Gets the value of the 'orderSide' field.
   */
  public java.lang.Integer getOrderSide() {
    return orderSide;
  }

  /**
   * Sets the value of the 'orderSide' field.
   * @param value the value to set.
   */
  public void setOrderSide(java.lang.Integer value) {
    this.orderSide = value;
  }

  /**
   * Gets the value of the 'orderType' field.
   */
  public java.lang.Integer getOrderType() {
    return orderType;
  }

  /**
   * Sets the value of the 'orderType' field.
   * @param value the value to set.
   */
  public void setOrderType(java.lang.Integer value) {
    this.orderType = value;
  }

  /**
   * Gets the value of the 'timeInForce' field.
   */
  public java.lang.Integer getTimeInForce() {
    return timeInForce;
  }

  /**
   * Sets the value of the 'timeInForce' field.
   * @param value the value to set.
   */
  public void setTimeInForce(java.lang.Integer value) {
    this.timeInForce = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   */
  public java.lang.Double getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Double value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'created' field.
   */
  public java.lang.String getCreated() {
    return created;
  }

  /**
   * Sets the value of the 'created' field.
   * @param value the value to set.
   */
  public void setCreated(java.lang.String value) {
    this.created = value;
  }

  /**
   * Gets the value of the 'exchangeAccount' field.
   */
  public java.lang.String getExchangeAccount() {
    return exchangeAccount;
  }

  /**
   * Sets the value of the 'exchangeAccount' field.
   * @param value the value to set.
   */
  public void setExchangeAccount(java.lang.String value) {
    this.exchangeAccount = value;
  }

  /**
   * Gets the value of the 'exchangeOrderId' field.
   */
  public java.lang.String getExchangeOrderId() {
    return exchangeOrderId;
  }

  /**
   * Sets the value of the 'exchangeOrderId' field.
   * @param value the value to set.
   */
  public void setExchangeOrderId(java.lang.String value) {
    this.exchangeOrderId = value;
  }

  /**
   * Gets the value of the 'clOrderId' field.
   */
  public java.lang.String getClOrderId() {
    return clOrderId;
  }

  /**
   * Sets the value of the 'clOrderId' field.
   * @param value the value to set.
   */
  public void setClOrderId(java.lang.String value) {
    this.clOrderId = value;
  }

  /**
   * Gets the value of the 'txId' field.
   */
  public java.lang.String getTxId() {
    return txId;
  }

  /**
   * Sets the value of the 'txId' field.
   * @param value the value to set.
   */
  public void setTxId(java.lang.String value) {
    this.txId = value;
  }

  /** Creates a new OrderUpdate RecordBuilder */
  public static com.cyanspring.avro.trading.OrderUpdate.Builder newBuilder() {
    return new com.cyanspring.avro.trading.OrderUpdate.Builder();
  }
  
  /** Creates a new OrderUpdate RecordBuilder by copying an existing Builder */
  public static com.cyanspring.avro.trading.OrderUpdate.Builder newBuilder(com.cyanspring.avro.trading.OrderUpdate.Builder other) {
    return new com.cyanspring.avro.trading.OrderUpdate.Builder(other);
  }
  
  /** Creates a new OrderUpdate RecordBuilder by copying an existing OrderUpdate instance */
  public static com.cyanspring.avro.trading.OrderUpdate.Builder newBuilder(com.cyanspring.avro.trading.OrderUpdate other) {
    return new com.cyanspring.avro.trading.OrderUpdate.Builder(other);
  }
  
  /**
   * RecordBuilder for OrderUpdate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderUpdate>
    implements org.apache.avro.data.RecordBuilder<OrderUpdate> {

    private int objectType;
    private int execType;
    private java.lang.String symbol;
    private int ordStatus;
    private int orderSide;
    private int orderType;
    private int timeInForce;
    private double price;
    private double quantity;
    private java.lang.String created;
    private java.lang.String exchangeAccount;
    private java.lang.String exchangeOrderId;
    private java.lang.String clOrderId;
    private java.lang.String txId;

    /** Creates a new Builder */
    private Builder() {
      super(com.cyanspring.avro.trading.OrderUpdate.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cyanspring.avro.trading.OrderUpdate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.execType)) {
        this.execType = data().deepCopy(fields()[1].schema(), other.execType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.symbol)) {
        this.symbol = data().deepCopy(fields()[2].schema(), other.symbol);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ordStatus)) {
        this.ordStatus = data().deepCopy(fields()[3].schema(), other.ordStatus);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.orderSide)) {
        this.orderSide = data().deepCopy(fields()[4].schema(), other.orderSide);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.orderType)) {
        this.orderType = data().deepCopy(fields()[5].schema(), other.orderType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timeInForce)) {
        this.timeInForce = data().deepCopy(fields()[6].schema(), other.timeInForce);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.price)) {
        this.price = data().deepCopy(fields()[7].schema(), other.price);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.quantity)) {
        this.quantity = data().deepCopy(fields()[8].schema(), other.quantity);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.created)) {
        this.created = data().deepCopy(fields()[9].schema(), other.created);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.exchangeAccount)) {
        this.exchangeAccount = data().deepCopy(fields()[10].schema(), other.exchangeAccount);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.exchangeOrderId)) {
        this.exchangeOrderId = data().deepCopy(fields()[11].schema(), other.exchangeOrderId);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.clOrderId)) {
        this.clOrderId = data().deepCopy(fields()[12].schema(), other.clOrderId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.txId)) {
        this.txId = data().deepCopy(fields()[13].schema(), other.txId);
        fieldSetFlags()[13] = true;
      }
    }
    
    /** Creates a Builder by copying an existing OrderUpdate instance */
    private Builder(com.cyanspring.avro.trading.OrderUpdate other) {
            super(com.cyanspring.avro.trading.OrderUpdate.SCHEMA$);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.execType)) {
        this.execType = data().deepCopy(fields()[1].schema(), other.execType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.symbol)) {
        this.symbol = data().deepCopy(fields()[2].schema(), other.symbol);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ordStatus)) {
        this.ordStatus = data().deepCopy(fields()[3].schema(), other.ordStatus);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.orderSide)) {
        this.orderSide = data().deepCopy(fields()[4].schema(), other.orderSide);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.orderType)) {
        this.orderType = data().deepCopy(fields()[5].schema(), other.orderType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timeInForce)) {
        this.timeInForce = data().deepCopy(fields()[6].schema(), other.timeInForce);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.price)) {
        this.price = data().deepCopy(fields()[7].schema(), other.price);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.quantity)) {
        this.quantity = data().deepCopy(fields()[8].schema(), other.quantity);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.created)) {
        this.created = data().deepCopy(fields()[9].schema(), other.created);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.exchangeAccount)) {
        this.exchangeAccount = data().deepCopy(fields()[10].schema(), other.exchangeAccount);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.exchangeOrderId)) {
        this.exchangeOrderId = data().deepCopy(fields()[11].schema(), other.exchangeOrderId);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.clOrderId)) {
        this.clOrderId = data().deepCopy(fields()[12].schema(), other.clOrderId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.txId)) {
        this.txId = data().deepCopy(fields()[13].schema(), other.txId);
        fieldSetFlags()[13] = true;
      }
    }

    /** Gets the value of the 'objectType' field */
    public java.lang.Integer getObjectType() {
      return objectType;
    }
    
    /** Sets the value of the 'objectType' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setObjectType(int value) {
      validate(fields()[0], value);
      this.objectType = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'objectType' field has been set */
    public boolean hasObjectType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'objectType' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearObjectType() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'execType' field */
    public java.lang.Integer getExecType() {
      return execType;
    }
    
    /** Sets the value of the 'execType' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setExecType(int value) {
      validate(fields()[1], value);
      this.execType = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'execType' field has been set */
    public boolean hasExecType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'execType' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearExecType() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'symbol' field */
    public java.lang.String getSymbol() {
      return symbol;
    }
    
    /** Sets the value of the 'symbol' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setSymbol(java.lang.String value) {
      validate(fields()[2], value);
      this.symbol = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'symbol' field has been set */
    public boolean hasSymbol() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'symbol' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ordStatus' field */
    public java.lang.Integer getOrdStatus() {
      return ordStatus;
    }
    
    /** Sets the value of the 'ordStatus' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setOrdStatus(int value) {
      validate(fields()[3], value);
      this.ordStatus = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ordStatus' field has been set */
    public boolean hasOrdStatus() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ordStatus' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearOrdStatus() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'orderSide' field */
    public java.lang.Integer getOrderSide() {
      return orderSide;
    }
    
    /** Sets the value of the 'orderSide' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setOrderSide(int value) {
      validate(fields()[4], value);
      this.orderSide = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'orderSide' field has been set */
    public boolean hasOrderSide() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'orderSide' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearOrderSide() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'orderType' field */
    public java.lang.Integer getOrderType() {
      return orderType;
    }
    
    /** Sets the value of the 'orderType' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setOrderType(int value) {
      validate(fields()[5], value);
      this.orderType = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'orderType' field has been set */
    public boolean hasOrderType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'orderType' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearOrderType() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'timeInForce' field */
    public java.lang.Integer getTimeInForce() {
      return timeInForce;
    }
    
    /** Sets the value of the 'timeInForce' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setTimeInForce(int value) {
      validate(fields()[6], value);
      this.timeInForce = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'timeInForce' field has been set */
    public boolean hasTimeInForce() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'timeInForce' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearTimeInForce() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.Double getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setPrice(double value) {
      validate(fields()[7], value);
      this.price = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'price' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearPrice() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'quantity' field */
    public java.lang.Double getQuantity() {
      return quantity;
    }
    
    /** Sets the value of the 'quantity' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setQuantity(double value) {
      validate(fields()[8], value);
      this.quantity = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'quantity' field has been set */
    public boolean hasQuantity() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'quantity' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearQuantity() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'created' field */
    public java.lang.String getCreated() {
      return created;
    }
    
    /** Sets the value of the 'created' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setCreated(java.lang.String value) {
      validate(fields()[9], value);
      this.created = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'created' field has been set */
    public boolean hasCreated() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'created' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearCreated() {
      created = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'exchangeAccount' field */
    public java.lang.String getExchangeAccount() {
      return exchangeAccount;
    }
    
    /** Sets the value of the 'exchangeAccount' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setExchangeAccount(java.lang.String value) {
      validate(fields()[10], value);
      this.exchangeAccount = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeAccount' field has been set */
    public boolean hasExchangeAccount() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'exchangeAccount' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearExchangeAccount() {
      exchangeAccount = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'exchangeOrderId' field */
    public java.lang.String getExchangeOrderId() {
      return exchangeOrderId;
    }
    
    /** Sets the value of the 'exchangeOrderId' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setExchangeOrderId(java.lang.String value) {
      validate(fields()[11], value);
      this.exchangeOrderId = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeOrderId' field has been set */
    public boolean hasExchangeOrderId() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'exchangeOrderId' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearExchangeOrderId() {
      exchangeOrderId = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'clOrderId' field */
    public java.lang.String getClOrderId() {
      return clOrderId;
    }
    
    /** Sets the value of the 'clOrderId' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setClOrderId(java.lang.String value) {
      validate(fields()[12], value);
      this.clOrderId = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'clOrderId' field has been set */
    public boolean hasClOrderId() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'clOrderId' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearClOrderId() {
      clOrderId = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'txId' field */
    public java.lang.String getTxId() {
      return txId;
    }
    
    /** Sets the value of the 'txId' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder setTxId(java.lang.String value) {
      validate(fields()[13], value);
      this.txId = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'txId' field has been set */
    public boolean hasTxId() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'txId' field */
    public com.cyanspring.avro.trading.OrderUpdate.Builder clearTxId() {
      txId = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    public OrderUpdate build() {
      try {
        OrderUpdate record = new OrderUpdate();
        record.objectType = fieldSetFlags()[0] ? this.objectType : (java.lang.Integer) defaultValue(fields()[0]);
        record.execType = fieldSetFlags()[1] ? this.execType : (java.lang.Integer) defaultValue(fields()[1]);
        record.symbol = fieldSetFlags()[2] ? this.symbol : (java.lang.String) defaultValue(fields()[2]);
        record.ordStatus = fieldSetFlags()[3] ? this.ordStatus : (java.lang.Integer) defaultValue(fields()[3]);
        record.orderSide = fieldSetFlags()[4] ? this.orderSide : (java.lang.Integer) defaultValue(fields()[4]);
        record.orderType = fieldSetFlags()[5] ? this.orderType : (java.lang.Integer) defaultValue(fields()[5]);
        record.timeInForce = fieldSetFlags()[6] ? this.timeInForce : (java.lang.Integer) defaultValue(fields()[6]);
        record.price = fieldSetFlags()[7] ? this.price : (java.lang.Double) defaultValue(fields()[7]);
        record.quantity = fieldSetFlags()[8] ? this.quantity : (java.lang.Double) defaultValue(fields()[8]);
        record.created = fieldSetFlags()[9] ? this.created : (java.lang.String) defaultValue(fields()[9]);
        record.exchangeAccount = fieldSetFlags()[10] ? this.exchangeAccount : (java.lang.String) defaultValue(fields()[10]);
        record.exchangeOrderId = fieldSetFlags()[11] ? this.exchangeOrderId : (java.lang.String) defaultValue(fields()[11]);
        record.clOrderId = fieldSetFlags()[12] ? this.clOrderId : (java.lang.String) defaultValue(fields()[12]);
        record.txId = fieldSetFlags()[13] ? this.txId : (java.lang.String) defaultValue(fields()[13]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
