/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cyanspring.avro.generate.trade.bean;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderUpdate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderUpdate\",\"namespace\":\"com.cyanspring.avro.generate.trade.bean\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"exchangeAccount\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"exchangeOrderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"quantity\",\"type\":\"double\"},{\"name\":\"cumQty\",\"type\":\"double\"},{\"name\":\"avgPx\",\"type\":\"double\"},{\"name\":\"execType\",\"type\":\"int\"},{\"name\":\"ordStatus\",\"type\":\"int\"},{\"name\":\"orderSide\",\"type\":\"int\"},{\"name\":\"orderType\",\"type\":\"int\"},{\"name\":\"timeInForce\",\"type\":\"int\"},{\"name\":\"created\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"clOrderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"txId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"msg\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int objectType;
  @Deprecated public java.lang.String orderId;
  @Deprecated public java.lang.String exchangeAccount;
  @Deprecated public java.lang.String exchangeOrderId;
  @Deprecated public java.lang.String symbol;
  @Deprecated public double price;
  @Deprecated public double quantity;
  @Deprecated public double cumQty;
  @Deprecated public double avgPx;
  @Deprecated public int execType;
  @Deprecated public int ordStatus;
  @Deprecated public int orderSide;
  @Deprecated public int orderType;
  @Deprecated public int timeInForce;
  @Deprecated public java.lang.String created;
  @Deprecated public java.lang.String clOrderId;
  @Deprecated public java.lang.String txId;
  @Deprecated public java.lang.String msg;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public OrderUpdate() {}

  /**
   * All-args constructor.
   */
  public OrderUpdate(java.lang.Integer objectType, java.lang.String orderId, java.lang.String exchangeAccount, java.lang.String exchangeOrderId, java.lang.String symbol, java.lang.Double price, java.lang.Double quantity, java.lang.Double cumQty, java.lang.Double avgPx, java.lang.Integer execType, java.lang.Integer ordStatus, java.lang.Integer orderSide, java.lang.Integer orderType, java.lang.Integer timeInForce, java.lang.String created, java.lang.String clOrderId, java.lang.String txId, java.lang.String msg) {
    this.objectType = objectType;
    this.orderId = orderId;
    this.exchangeAccount = exchangeAccount;
    this.exchangeOrderId = exchangeOrderId;
    this.symbol = symbol;
    this.price = price;
    this.quantity = quantity;
    this.cumQty = cumQty;
    this.avgPx = avgPx;
    this.execType = execType;
    this.ordStatus = ordStatus;
    this.orderSide = orderSide;
    this.orderType = orderType;
    this.timeInForce = timeInForce;
    this.created = created;
    this.clOrderId = clOrderId;
    this.txId = txId;
    this.msg = msg;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return objectType;
    case 1: return orderId;
    case 2: return exchangeAccount;
    case 3: return exchangeOrderId;
    case 4: return symbol;
    case 5: return price;
    case 6: return quantity;
    case 7: return cumQty;
    case 8: return avgPx;
    case 9: return execType;
    case 10: return ordStatus;
    case 11: return orderSide;
    case 12: return orderType;
    case 13: return timeInForce;
    case 14: return created;
    case 15: return clOrderId;
    case 16: return txId;
    case 17: return msg;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: objectType = (java.lang.Integer)value$; break;
    case 1: orderId = (java.lang.String)value$; break;
    case 2: exchangeAccount = (java.lang.String)value$; break;
    case 3: exchangeOrderId = (java.lang.String)value$; break;
    case 4: symbol = (java.lang.String)value$; break;
    case 5: price = (java.lang.Double)value$; break;
    case 6: quantity = (java.lang.Double)value$; break;
    case 7: cumQty = (java.lang.Double)value$; break;
    case 8: avgPx = (java.lang.Double)value$; break;
    case 9: execType = (java.lang.Integer)value$; break;
    case 10: ordStatus = (java.lang.Integer)value$; break;
    case 11: orderSide = (java.lang.Integer)value$; break;
    case 12: orderType = (java.lang.Integer)value$; break;
    case 13: timeInForce = (java.lang.Integer)value$; break;
    case 14: created = (java.lang.String)value$; break;
    case 15: clOrderId = (java.lang.String)value$; break;
    case 16: txId = (java.lang.String)value$; break;
    case 17: msg = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'objectType' field.
   */
  public java.lang.Integer getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the 'objectType' field.
   * @param value the value to set.
   */
  public void setObjectType(java.lang.Integer value) {
    this.objectType = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'exchangeAccount' field.
   */
  public java.lang.String getExchangeAccount() {
    return exchangeAccount;
  }

  /**
   * Sets the value of the 'exchangeAccount' field.
   * @param value the value to set.
   */
  public void setExchangeAccount(java.lang.String value) {
    this.exchangeAccount = value;
  }

  /**
   * Gets the value of the 'exchangeOrderId' field.
   */
  public java.lang.String getExchangeOrderId() {
    return exchangeOrderId;
  }

  /**
   * Sets the value of the 'exchangeOrderId' field.
   * @param value the value to set.
   */
  public void setExchangeOrderId(java.lang.String value) {
    this.exchangeOrderId = value;
  }

  /**
   * Gets the value of the 'symbol' field.
   */
  public java.lang.String getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   */
  public java.lang.Double getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Double value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'cumQty' field.
   */
  public java.lang.Double getCumQty() {
    return cumQty;
  }

  /**
   * Sets the value of the 'cumQty' field.
   * @param value the value to set.
   */
  public void setCumQty(java.lang.Double value) {
    this.cumQty = value;
  }

  /**
   * Gets the value of the 'avgPx' field.
   */
  public java.lang.Double getAvgPx() {
    return avgPx;
  }

  /**
   * Sets the value of the 'avgPx' field.
   * @param value the value to set.
   */
  public void setAvgPx(java.lang.Double value) {
    this.avgPx = value;
  }

  /**
   * Gets the value of the 'execType' field.
   */
  public java.lang.Integer getExecType() {
    return execType;
  }

  /**
   * Sets the value of the 'execType' field.
   * @param value the value to set.
   */
  public void setExecType(java.lang.Integer value) {
    this.execType = value;
  }

  /**
   * Gets the value of the 'ordStatus' field.
   */
  public java.lang.Integer getOrdStatus() {
    return ordStatus;
  }

  /**
   * Sets the value of the 'ordStatus' field.
   * @param value the value to set.
   */
  public void setOrdStatus(java.lang.Integer value) {
    this.ordStatus = value;
  }

  /**
   * Gets the value of the 'orderSide' field.
   */
  public java.lang.Integer getOrderSide() {
    return orderSide;
  }

  /**
   * Sets the value of the 'orderSide' field.
   * @param value the value to set.
   */
  public void setOrderSide(java.lang.Integer value) {
    this.orderSide = value;
  }

  /**
   * Gets the value of the 'orderType' field.
   */
  public java.lang.Integer getOrderType() {
    return orderType;
  }

  /**
   * Sets the value of the 'orderType' field.
   * @param value the value to set.
   */
  public void setOrderType(java.lang.Integer value) {
    this.orderType = value;
  }

  /**
   * Gets the value of the 'timeInForce' field.
   */
  public java.lang.Integer getTimeInForce() {
    return timeInForce;
  }

  /**
   * Sets the value of the 'timeInForce' field.
   * @param value the value to set.
   */
  public void setTimeInForce(java.lang.Integer value) {
    this.timeInForce = value;
  }

  /**
   * Gets the value of the 'created' field.
   */
  public java.lang.String getCreated() {
    return created;
  }

  /**
   * Sets the value of the 'created' field.
   * @param value the value to set.
   */
  public void setCreated(java.lang.String value) {
    this.created = value;
  }

  /**
   * Gets the value of the 'clOrderId' field.
   */
  public java.lang.String getClOrderId() {
    return clOrderId;
  }

  /**
   * Sets the value of the 'clOrderId' field.
   * @param value the value to set.
   */
  public void setClOrderId(java.lang.String value) {
    this.clOrderId = value;
  }

  /**
   * Gets the value of the 'txId' field.
   */
  public java.lang.String getTxId() {
    return txId;
  }

  /**
   * Sets the value of the 'txId' field.
   * @param value the value to set.
   */
  public void setTxId(java.lang.String value) {
    this.txId = value;
  }

  /**
   * Gets the value of the 'msg' field.
   */
  public java.lang.String getMsg() {
    return msg;
  }

  /**
   * Sets the value of the 'msg' field.
   * @param value the value to set.
   */
  public void setMsg(java.lang.String value) {
    this.msg = value;
  }

  /** Creates a new OrderUpdate RecordBuilder */
  public static com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder newBuilder() {
    return new com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder();
  }
  
  /** Creates a new OrderUpdate RecordBuilder by copying an existing Builder */
  public static com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder newBuilder(com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder other) {
    return new com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder(other);
  }
  
  /** Creates a new OrderUpdate RecordBuilder by copying an existing OrderUpdate instance */
  public static com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder newBuilder(com.cyanspring.avro.generate.trade.bean.OrderUpdate other) {
    return new com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder(other);
  }
  
  /**
   * RecordBuilder for OrderUpdate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderUpdate>
    implements org.apache.avro.data.RecordBuilder<OrderUpdate> {

    private int objectType;
    private java.lang.String orderId;
    private java.lang.String exchangeAccount;
    private java.lang.String exchangeOrderId;
    private java.lang.String symbol;
    private double price;
    private double quantity;
    private double cumQty;
    private double avgPx;
    private int execType;
    private int ordStatus;
    private int orderSide;
    private int orderType;
    private int timeInForce;
    private java.lang.String created;
    private java.lang.String clOrderId;
    private java.lang.String txId;
    private java.lang.String msg;

    /** Creates a new Builder */
    private Builder() {
      super(com.cyanspring.avro.generate.trade.bean.OrderUpdate.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.exchangeAccount)) {
        this.exchangeAccount = data().deepCopy(fields()[2].schema(), other.exchangeAccount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exchangeOrderId)) {
        this.exchangeOrderId = data().deepCopy(fields()[3].schema(), other.exchangeOrderId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.symbol)) {
        this.symbol = data().deepCopy(fields()[4].schema(), other.symbol);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.price)) {
        this.price = data().deepCopy(fields()[5].schema(), other.price);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.quantity)) {
        this.quantity = data().deepCopy(fields()[6].schema(), other.quantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cumQty)) {
        this.cumQty = data().deepCopy(fields()[7].schema(), other.cumQty);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.avgPx)) {
        this.avgPx = data().deepCopy(fields()[8].schema(), other.avgPx);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.execType)) {
        this.execType = data().deepCopy(fields()[9].schema(), other.execType);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ordStatus)) {
        this.ordStatus = data().deepCopy(fields()[10].schema(), other.ordStatus);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.orderSide)) {
        this.orderSide = data().deepCopy(fields()[11].schema(), other.orderSide);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.orderType)) {
        this.orderType = data().deepCopy(fields()[12].schema(), other.orderType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.timeInForce)) {
        this.timeInForce = data().deepCopy(fields()[13].schema(), other.timeInForce);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.created)) {
        this.created = data().deepCopy(fields()[14].schema(), other.created);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.clOrderId)) {
        this.clOrderId = data().deepCopy(fields()[15].schema(), other.clOrderId);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.txId)) {
        this.txId = data().deepCopy(fields()[16].schema(), other.txId);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.msg)) {
        this.msg = data().deepCopy(fields()[17].schema(), other.msg);
        fieldSetFlags()[17] = true;
      }
    }
    
    /** Creates a Builder by copying an existing OrderUpdate instance */
    private Builder(com.cyanspring.avro.generate.trade.bean.OrderUpdate other) {
            super(com.cyanspring.avro.generate.trade.bean.OrderUpdate.SCHEMA$);
      if (isValidValue(fields()[0], other.objectType)) {
        this.objectType = data().deepCopy(fields()[0].schema(), other.objectType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.exchangeAccount)) {
        this.exchangeAccount = data().deepCopy(fields()[2].schema(), other.exchangeAccount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exchangeOrderId)) {
        this.exchangeOrderId = data().deepCopy(fields()[3].schema(), other.exchangeOrderId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.symbol)) {
        this.symbol = data().deepCopy(fields()[4].schema(), other.symbol);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.price)) {
        this.price = data().deepCopy(fields()[5].schema(), other.price);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.quantity)) {
        this.quantity = data().deepCopy(fields()[6].schema(), other.quantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cumQty)) {
        this.cumQty = data().deepCopy(fields()[7].schema(), other.cumQty);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.avgPx)) {
        this.avgPx = data().deepCopy(fields()[8].schema(), other.avgPx);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.execType)) {
        this.execType = data().deepCopy(fields()[9].schema(), other.execType);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ordStatus)) {
        this.ordStatus = data().deepCopy(fields()[10].schema(), other.ordStatus);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.orderSide)) {
        this.orderSide = data().deepCopy(fields()[11].schema(), other.orderSide);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.orderType)) {
        this.orderType = data().deepCopy(fields()[12].schema(), other.orderType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.timeInForce)) {
        this.timeInForce = data().deepCopy(fields()[13].schema(), other.timeInForce);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.created)) {
        this.created = data().deepCopy(fields()[14].schema(), other.created);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.clOrderId)) {
        this.clOrderId = data().deepCopy(fields()[15].schema(), other.clOrderId);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.txId)) {
        this.txId = data().deepCopy(fields()[16].schema(), other.txId);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.msg)) {
        this.msg = data().deepCopy(fields()[17].schema(), other.msg);
        fieldSetFlags()[17] = true;
      }
    }

    /** Gets the value of the 'objectType' field */
    public java.lang.Integer getObjectType() {
      return objectType;
    }
    
    /** Sets the value of the 'objectType' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setObjectType(int value) {
      validate(fields()[0], value);
      this.objectType = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'objectType' field has been set */
    public boolean hasObjectType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'objectType' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearObjectType() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'orderId' field */
    public java.lang.String getOrderId() {
      return orderId;
    }
    
    /** Sets the value of the 'orderId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setOrderId(java.lang.String value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'orderId' field has been set */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'orderId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'exchangeAccount' field */
    public java.lang.String getExchangeAccount() {
      return exchangeAccount;
    }
    
    /** Sets the value of the 'exchangeAccount' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setExchangeAccount(java.lang.String value) {
      validate(fields()[2], value);
      this.exchangeAccount = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeAccount' field has been set */
    public boolean hasExchangeAccount() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'exchangeAccount' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearExchangeAccount() {
      exchangeAccount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'exchangeOrderId' field */
    public java.lang.String getExchangeOrderId() {
      return exchangeOrderId;
    }
    
    /** Sets the value of the 'exchangeOrderId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setExchangeOrderId(java.lang.String value) {
      validate(fields()[3], value);
      this.exchangeOrderId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeOrderId' field has been set */
    public boolean hasExchangeOrderId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'exchangeOrderId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearExchangeOrderId() {
      exchangeOrderId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'symbol' field */
    public java.lang.String getSymbol() {
      return symbol;
    }
    
    /** Sets the value of the 'symbol' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setSymbol(java.lang.String value) {
      validate(fields()[4], value);
      this.symbol = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'symbol' field has been set */
    public boolean hasSymbol() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'symbol' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.Double getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setPrice(double value) {
      validate(fields()[5], value);
      this.price = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'price' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearPrice() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'quantity' field */
    public java.lang.Double getQuantity() {
      return quantity;
    }
    
    /** Sets the value of the 'quantity' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setQuantity(double value) {
      validate(fields()[6], value);
      this.quantity = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'quantity' field has been set */
    public boolean hasQuantity() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'quantity' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearQuantity() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'cumQty' field */
    public java.lang.Double getCumQty() {
      return cumQty;
    }
    
    /** Sets the value of the 'cumQty' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setCumQty(double value) {
      validate(fields()[7], value);
      this.cumQty = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'cumQty' field has been set */
    public boolean hasCumQty() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'cumQty' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearCumQty() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'avgPx' field */
    public java.lang.Double getAvgPx() {
      return avgPx;
    }
    
    /** Sets the value of the 'avgPx' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setAvgPx(double value) {
      validate(fields()[8], value);
      this.avgPx = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'avgPx' field has been set */
    public boolean hasAvgPx() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'avgPx' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearAvgPx() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'execType' field */
    public java.lang.Integer getExecType() {
      return execType;
    }
    
    /** Sets the value of the 'execType' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setExecType(int value) {
      validate(fields()[9], value);
      this.execType = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'execType' field has been set */
    public boolean hasExecType() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'execType' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearExecType() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'ordStatus' field */
    public java.lang.Integer getOrdStatus() {
      return ordStatus;
    }
    
    /** Sets the value of the 'ordStatus' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setOrdStatus(int value) {
      validate(fields()[10], value);
      this.ordStatus = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'ordStatus' field has been set */
    public boolean hasOrdStatus() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'ordStatus' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearOrdStatus() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'orderSide' field */
    public java.lang.Integer getOrderSide() {
      return orderSide;
    }
    
    /** Sets the value of the 'orderSide' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setOrderSide(int value) {
      validate(fields()[11], value);
      this.orderSide = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'orderSide' field has been set */
    public boolean hasOrderSide() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'orderSide' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearOrderSide() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'orderType' field */
    public java.lang.Integer getOrderType() {
      return orderType;
    }
    
    /** Sets the value of the 'orderType' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setOrderType(int value) {
      validate(fields()[12], value);
      this.orderType = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'orderType' field has been set */
    public boolean hasOrderType() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'orderType' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearOrderType() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'timeInForce' field */
    public java.lang.Integer getTimeInForce() {
      return timeInForce;
    }
    
    /** Sets the value of the 'timeInForce' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setTimeInForce(int value) {
      validate(fields()[13], value);
      this.timeInForce = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'timeInForce' field has been set */
    public boolean hasTimeInForce() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'timeInForce' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearTimeInForce() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'created' field */
    public java.lang.String getCreated() {
      return created;
    }
    
    /** Sets the value of the 'created' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setCreated(java.lang.String value) {
      validate(fields()[14], value);
      this.created = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'created' field has been set */
    public boolean hasCreated() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'created' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearCreated() {
      created = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'clOrderId' field */
    public java.lang.String getClOrderId() {
      return clOrderId;
    }
    
    /** Sets the value of the 'clOrderId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setClOrderId(java.lang.String value) {
      validate(fields()[15], value);
      this.clOrderId = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'clOrderId' field has been set */
    public boolean hasClOrderId() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'clOrderId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearClOrderId() {
      clOrderId = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'txId' field */
    public java.lang.String getTxId() {
      return txId;
    }
    
    /** Sets the value of the 'txId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setTxId(java.lang.String value) {
      validate(fields()[16], value);
      this.txId = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'txId' field has been set */
    public boolean hasTxId() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'txId' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearTxId() {
      txId = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'msg' field */
    public java.lang.String getMsg() {
      return msg;
    }
    
    /** Sets the value of the 'msg' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder setMsg(java.lang.String value) {
      validate(fields()[17], value);
      this.msg = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'msg' field has been set */
    public boolean hasMsg() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'msg' field */
    public com.cyanspring.avro.generate.trade.bean.OrderUpdate.Builder clearMsg() {
      msg = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    public OrderUpdate build() {
      try {
        OrderUpdate record = new OrderUpdate();
        record.objectType = fieldSetFlags()[0] ? this.objectType : (java.lang.Integer) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.lang.String) defaultValue(fields()[1]);
        record.exchangeAccount = fieldSetFlags()[2] ? this.exchangeAccount : (java.lang.String) defaultValue(fields()[2]);
        record.exchangeOrderId = fieldSetFlags()[3] ? this.exchangeOrderId : (java.lang.String) defaultValue(fields()[3]);
        record.symbol = fieldSetFlags()[4] ? this.symbol : (java.lang.String) defaultValue(fields()[4]);
        record.price = fieldSetFlags()[5] ? this.price : (java.lang.Double) defaultValue(fields()[5]);
        record.quantity = fieldSetFlags()[6] ? this.quantity : (java.lang.Double) defaultValue(fields()[6]);
        record.cumQty = fieldSetFlags()[7] ? this.cumQty : (java.lang.Double) defaultValue(fields()[7]);
        record.avgPx = fieldSetFlags()[8] ? this.avgPx : (java.lang.Double) defaultValue(fields()[8]);
        record.execType = fieldSetFlags()[9] ? this.execType : (java.lang.Integer) defaultValue(fields()[9]);
        record.ordStatus = fieldSetFlags()[10] ? this.ordStatus : (java.lang.Integer) defaultValue(fields()[10]);
        record.orderSide = fieldSetFlags()[11] ? this.orderSide : (java.lang.Integer) defaultValue(fields()[11]);
        record.orderType = fieldSetFlags()[12] ? this.orderType : (java.lang.Integer) defaultValue(fields()[12]);
        record.timeInForce = fieldSetFlags()[13] ? this.timeInForce : (java.lang.Integer) defaultValue(fields()[13]);
        record.created = fieldSetFlags()[14] ? this.created : (java.lang.String) defaultValue(fields()[14]);
        record.clOrderId = fieldSetFlags()[15] ? this.clOrderId : (java.lang.String) defaultValue(fields()[15]);
        record.txId = fieldSetFlags()[16] ? this.txId : (java.lang.String) defaultValue(fields()[16]);
        record.msg = fieldSetFlags()[17] ? this.msg : (java.lang.String) defaultValue(fields()[17]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
