// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.cyanspring.avro.generate.@base
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class StateUpdate : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"StateUpdate\",\"namespace\":\"com.cyanspring.avro.generate.b" +
				"ase\",\"fields\":[{\"name\":\"objectType\",\"type\":\"int\"},{\"name\":\"exchangeAccount\",\"typ" +
				"e\":\"string\"},{\"name\":\"online\",\"type\":\"boolean\"}]}");
		private int _objectType;
		private string _exchangeAccount;
		private bool _online;
		public virtual Schema Schema
		{
			get
			{
				return StateUpdate._SCHEMA;
			}
		}
		public int objectType
		{
			get
			{
				return this._objectType;
			}
			set
			{
				this._objectType = value;
			}
		}
		public string exchangeAccount
		{
			get
			{
				return this._exchangeAccount;
			}
			set
			{
				this._exchangeAccount = value;
			}
		}
		public bool online
		{
			get
			{
				return this._online;
			}
			set
			{
				this._online = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.objectType;
			case 1: return this.exchangeAccount;
			case 2: return this.online;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.objectType = (System.Int32)fieldValue; break;
			case 1: this.exchangeAccount = (System.String)fieldValue; break;
			case 2: this.online = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
