package com.cyanspring.common.message;

public enum Message {
	// exception start with 000
	EXCEPTION_MESSAGE,
	NONE_MATCHED_MESSAGE,
	EMPTY_MESSAGE,
	// system errors start with 100
	RECEIVE_HANDLE_ERROR,
	ACTIVEMQ_CONNECT_FAILED,
	ACTIVEMQ_CLOSE_FAILED,
	ACTIVEMQ_TIMEOUT,
	ACTIVE_IDLE,
	PACKET_FORMAT_WRONG,
	CONNECTION_NOT_AVAILABLE,	
	CONNECTION_BROKEN,
	INVALID_CMD_PACKET,
	UNSUPPORTED_CMD_PACKET,
	SERVER_NOT_AVAILABLE,
	SEND_FRAME_FAILED,			
	NONE_SET_USER,
	NONE_SET_CALLBACK,
	NONE_SET_CONNECTION_CONFIG,
	// business errors start with 200
	PREMIUM_FOLLOW_INFO_INCOMPLETE,
	PREMIUM_FOLLOW_REQUEST_TIMEOUT,
	SYMBOLIST_ERROR,
	SEARCH_SYMBOL_ERROR,
	PRICE_ALERT_ERROR,
	TRADE_ALERT_ERROR,
	NO_ALERT_DATA,
	REF_SYMBOL_NOT_FOUND, // Ref packet's symbols not found
	REF_SYMBOL_DUPLICATED,
	REF_SYMBOL_NOT_VALID, // Ref packet's symbols not valid
	REF_SYMBOL_RUNTIME_ERROR, // Ref packet's symbols runtime error
	USER_HAVE_NOT_SUBSCRIBE_SYMBOL,// User didn't subscribe symbol
	USER_NONE_PERMISSION, // User doesn't have enough permission
	SUBSCRIBE_LIMITATION, // Subscribe count is limited
	SEQUENCE_NUMBER_ERROR,
	NOT_SUPPORT_FREQUENCE,//Chart Error
	
	// api errors start with 300
	SEVER_NOT_CONNECTED,
	USER_NEED_LOGIN_BEFORE_EVENTS,
	EVENT_TYPE_NOT_SUPPORT,
	ACCOUNT_NOT_MATCH,
	LOGIN_BLOCKED,
	
	// order errors start with 400
	ACTION_CANCELLED,
	ORDER_PROCESSING,
	ORDER_NOT_CAHNGE,
	ORDER_ID_NOT_FOUND,
	ORDER_SIDE_NOT_SUPPORT,
	ORDER_TYPE_NOT_SUPPORT,
	ACCOUNT_NOT_EXIST,
	USER_NOT_LOGIN,
	ENTER_ORDER_ERROR,
	AMEND_ORDER_ERROR,
	CANCEL_ORDER_ERROR,
	AMEND_PARAM_SHORT,
	CLOSE_ORDER_ERROR,
	TX_ID_ILLEGAL,
	ORDER_REASON_NOT_SUPPORT,
	ALERT_TYPE_NOT_SUPPORT,
	NONE_ASSIGN_PRICE,
	

	// user errors start with 500
	CREATE_USER_FAILED,
	USER_LOGIN_FAILED,
	CHANGE_USER_PWD_FAILED,
	USER_LOGIN_APPSERVER_FAILED,
	WRONG_USER_TYPE,
	EMPTY_PWD,
	PREMIUM_FOLLOW_ERROR,
	ACCOUNT_RESET_ERROR,
	INVALID_USER_INFO,
	
	// client errors start with 600
	NEED_RESTART_APP,
	SERVER_IN_MAINTAINING,
	ANOTHER_DEVICE_ALREADY_LOGIN,
	NEW_VERSION_NEED_DOWNLOAD,
	NEW_VERSION_AVAILABLE,
	MESSAGE_ARRIVED,
	CLIENT_NOT_CONNECT,
	CLIENT_NOT_DISCONNECT,
	CLIENT_PARAM_ERROR,
	CLIENT_IDLE,
	CLIENT_SEND_DISCONNECT,
	CLIENT_VERSION_ERROR,

	//DB errors start with 700
	SQL_SYNTAX_ERROR,
	DATA_NOT_FOUND,
	DATA_ALREADY_EXIST,
	WRONG_ACTION,

	//quote errors start with 800
	INVALID_QUOTE_ID,
	QUOTE_NOT_SUBSCRIBE,
	NO_QUOTE_DATA,
	NO_DATA_ERROR,
	NO_MORE_DATA;

	
	
}
